ydlidar_ros2_driver_node:
  ros__parameters:
    port: /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0
    frame_id: laser_frame
    baudrate: 230400
    lidar_type: 1
    sample_rate: 9
    auto_reconnect: true
